### ISSUE TITLE
Include photons

### ISSUE THREAD

**Issue by artlbv** [cms-l1-dpg/Phase2-L1MenuTools#4]
Cache-ing of photons is now handled correctly (see [here](https://github.com/bonanomi/Phase2-L1MenuTools/blob/main/objectPerformance/cfg_caching/V22.yaml#L34-40)), but in the computation of the matching efficiency, two different objects are used:

* numerator: `TkIsoPhotonTrackID_PTEta15_000000`
* denominator: `TkPhotonTrackIDIsoNoMatch_PTEta15_000000`
defined as:

`TkPhotonTrackID TkIsoPhotonTrackID Photon -1 2.4 -1 0.15 UseFlag 0.15 -1 0.25 0.205 TkIsoPhotonTrackID 100 0 150 30 -3 3 200 0 0.6 100 0 10 EG`

and

`TkPhotonTrackID TkPhotonTrackIDIso Photon -1 2.4 -1 0.15 UseFlag 0.15 -1 -1 -1 TkPhotonTrackIDIso 100 0 150 30 -3 3 200 0 0.6 100 0 10 EG`

while the current version of the framework would compute the matching efficiency as the ratio of `TkIsoPhotonTrackID_PTEta15_000000` to `TkIsoPhotonTrackIDNoMatch_PTEta15_000000` (as for all the other objects, where the numerator is the distribution of matched objects and the denominator the unmatched ones, in both cases with L1 pT cut at 0 GeV, i.e. no cut).

**Comment by bonanomi** [comment]
Hi @artlbv IIUC you have included config files for photons and we do not want to have a different treatment for numerator and denominator objects, as it was not clear where this distinction originally came from. If that is the case, I suggest we close this issue because now photons are indeed included in the framework.
